<?php $pageTitle='PC World Geek | 24/7 Independent Tech Support UK';$pageDescription='24/7 independent tech support for computers, printers, Wi-Fi, routers and home technology.';require 'header.php';?>
<main>
<section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">INDEPENDENT UK TECH SUPPORT</span><h1>Technology problems.<br><em>Real help, when you need it.</em></h1><p class="lead">24/7 support options for computers, printers, Wi-Fi, routers and everyday technology. Choose one-off help or ongoing membership.</p><div class="actions"><a class="btn primary" href="booking.php">Book Support →</a><a class="btn ghost" href="memberships.php">View Memberships</a></div><div class="checks"><span>✓ Remote support</span><span>✓ Clear pricing</span><span>✓ UK-focused service</span></div></div>
<div class="hero-card"><div class="availability"><i></i> SUPPORT OPTIONS AVAILABLE</div><h2>What do you need help with?</h2><div class="quick"><a href="services.php#computer">💻 <span>Computer & laptop</span></a><a href="services.php#printer">🖨 <span>Printer</span></a><a href="services.php#wifi">📶 <span>Wi-Fi & router</span></a><a href="services.php#security">🛡 <span>Security</span></a></div><a class="arrowlink" href="services.php">Explore all services →</a></div></div></section>
<section class="trust"><div class="wrap trustgrid"><div><b>24/7</b><span>Support options*</span></div><div><b>£49+</b><span>One-off support from</span></div><div><b>£14.99</b><span>Monthly membership from</span></div><div><b>Remote</b><span>Help from home</span></div></div></section>
<section class="section"><div class="wrap"><div class="heading"><span class="eyebrow">POPULAR SUPPORT</span><h2>Help with the technology you rely on.</h2><p>Clear service options for common home and small-office technology problems.</p></div><div class="service-grid">
<a class="service-tile" href="services.php#computer"><span>01</span><h3>Computer & laptop</h3><p>Slow, frozen, crashing, setup and software problems.</p><b>From £69 →</b></a>
<a class="service-tile" href="services.php#printer"><span>02</span><h3>Printer support</h3><p>Setup, wireless connection, drivers and print issues.</p><b>From £59 →</b></a>
<a class="service-tile" href="services.php#wifi"><span>03</span><h3>Wi-Fi & routers</h3><p>Connectivity, configuration and home network troubleshooting.</p><b>From £59 →</b></a>
<a class="service-tile" href="services.php#security"><span>04</span><h3>Security & malware</h3><p>Security setup and troubleshooting for supported devices.</p><b>From £79 →</b></a>
</div></div></section>
<section class="dark"><div class="wrap split"><div><span class="eyebrow">MEMBERSHIPS</span><h2>Support beyond a single problem.</h2><p>For customers who want recurring access to technology support, choose monthly or annual membership.</p><a class="btn orange" href="memberships.php">Compare Memberships →</a></div><div class="price-mini"><div><span>MONTHLY</span><strong>£14.99</strong><small>per month</small></div><div><span>ANNUAL</span><strong>£149.99</strong><small>per year</small></div></div></div></section>
<section class="section"><div class="wrap"><div class="heading"><span class="eyebrow">BUILT FOR TRUST</span><h2>Simple, transparent support.</h2></div><div class="features"><div><b>01</b><h3>Know the price</h3><p>Service and membership prices are displayed before checkout. Recurring billing is clearly identified.</p></div><div><b>02</b><h3>Know who you're dealing with</h3><p>PC World Geek is an independent business and does not claim affiliation with other brands.</p></div><div><b>03</b><h3>Know what happens next</h3><p>Book support, choose a service, and receive clear information about the support process.</p></div></div></div></section>
</main><?php require 'footer.php';?>
