CREATE DATABASE IF NOT EXISTS pcworldgeek CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pcworldgeek;

CREATE TABLE users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE bookings (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(190) NOT NULL,
 phone VARCHAR(50) NOT NULL,
 service VARCHAR(80) NOT NULL,
 preferred_date DATE NOT NULL,
 preferred_time VARCHAR(20) NOT NULL,
 notes TEXT NULL,
 status ENUM('pending','confirmed','completed','cancelled') DEFAULT 'pending',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 stripe_session_id VARCHAR(255) NOT NULL UNIQUE,
 stripe_customer_id VARCHAR(255) NULL,
 product_key VARCHAR(80) NOT NULL,
 amount_pence INT NOT NULL,
 currency CHAR(3) NOT NULL DEFAULT 'gbp',
 payment_status VARCHAR(50) NOT NULL DEFAULT 'pending',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
